### ISSUE TITLE
MultiQC module fails with bcbio_vm

### ISSUE THREAD

**Issue by coughls** [MultiQC/MultiQC_bcbio#20]
I ran bcbio_vm on one sample on one machine (bcbio_vm.py run -n 15 ../config/samples.yaml)  but got the following error at the multiqc stage. Any help greatly appreciated, thanks. 
```
[2018-03-07T08:04Z] summarize metrics
[2018-03-07T08:04Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=/usr/local/share/bcbio-nextgen/anaconda/bin:$PATH &&  /usr/local/share/bcbio-nextgen/anaconda/bin/multiqc -f -l /mnt/work/qc/multiqc/list_files.tx
t  -o /mnt/work/bcbiotx/tmpu8rvWt
[INFO   ]         multiqc : This is MultiQC v1.4
[INFO   ]         multiqc : Template    : default
Searching 20 files..
[INFO   ] goleft_indexcov : Found goleft indexcov ROC reports for 1 samples
[INFO   ] goleft_indexcov : Found goleft indexcov bin reports for 1 samples
[INFO   ]           bcbio : Found 1 reports
[ERROR  ]         multiqc : Oops! The 'bcbio' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    /mnt/work/qc/multiqc/report/metrics/target_info.yaml
============================================================
Module bcbio raised an exception: Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/bin/multiqc", line 427, in multiqc
    output = mod()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/multiqc_bcbio/bcbio.py", line 111, in __init__
    if "coverage_avg_chart" in coverage_avg_plot:
TypeError: argument of type 'NoneType' is not iterable
============================================================
[INFO   ]        samtools : Found 1 stats reports
[INFO   ]        samtools : Found 1 idxstats reports
[INFO   ]        bcftools : Found 1 stats reports
[INFO   ]          snpeff : Found 1 reports
[INFO   ]          fastqc : Found 1 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : ../../bcbiotx/tmpu8rvWt/multiqc_report.html
[INFO   ]         multiqc : Data        : ../../bcbiotx/tmpu8rvWt/multiqc_data
[INFO   ]         multiqc : MultiQC complete
' returned non-zero exit status 1
Uncaught exception occurred
Traceback (most recent call last):
  File "/home/ubuntu/projects/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/ubuntu/projects/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'docker attach --no-stdin 893c59ed13112855586eb83f0c287f6591dc431711474501b296d5cfa87f657b
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=/usr/local/share/bcbio-nextgen/anaconda/bin:$PATH &&  /usr/local/share/bcbio-nextgen/anaconda/bin/multiqc -f -l /mnt/work/qc/multiqc/list_files.txt  -o /mnt/work/bcbiotx/tmpu8rvWt
[INFO   ]         multiqc : This is MultiQC v1.4
[INFO   ]         multiqc : Template    : default
Searching 20 files..
[INFO   ] goleft_indexcov : Found goleft indexcov ROC reports for 1 samples
[INFO   ] goleft_indexcov : Found goleft indexcov bin reports for 1 samples
[INFO   ]           bcbio : Found 1 reports
[ERROR  ]         multiqc : Oops! The 'bcbio' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    /mnt/work/qc/multiqc/report/metrics/target_info.yaml
============================================================
Module bcbio raised an exception: Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/bin/multiqc", line 427, in multiqc
    output = mod()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/multiqc_bcbio/bcbio.py", line 111, in __init__
    if "coverage_avg_chart" in coverage_avg_plot:
TypeError: argument of type 'NoneType' is not iterable
============================================================
[INFO   ]        samtools : Found 1 stats reports
[INFO   ]        samtools : Found 1 idxstats reports
[INFO   ]        bcftools : Found 1 stats reports
[INFO   ]          snpeff : Found 1 reports
[INFO   ]          fastqc : Found 1 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : ../../bcbiotx/tmpu8rvWt/multiqc_report.html
[INFO   ]         multiqc : Data        : ../../bcbiotx/tmpu8rvWt/multiqc_data
[INFO   ]         multiqc : MultiQC complete
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 186, in variant2pipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 38, in generate_parallel
    samples = run_parallel("multiqc_summary", [samples])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 207, in multiqc_summary
   return multiqc.summary(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/qc/multiqc.py", line 62, in summary
    do.run(cmd.format(**locals()), "Run multiqc")
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export PATH=/usr/local/share/bcbio-nextgen/anaconda/bin:$PATH &&  /usr/local/share/bcbio-nextgen/anaconda/bin/multiqc -f -l /mnt/work/qc/multiqc/list_files.txt  -o /mnt/work/bcbiotx/tmpu8rvWt
[INFO   ]         multiqc : This is MultiQC v1.4
[INFO   ]         multiqc : Template    : default
Searching 20 files..
[INFO   ] goleft_indexcov : Found goleft indexcov ROC reports for 1 samples
[INFO   ] goleft_indexcov : Found goleft indexcov bin reports for 1 samples
[INFO   ]           bcbio : Found 1 reports
[ERROR  ]         multiqc : Oops! The 'bcbio' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    /mnt/work/qc/multiqc/report/metrics/target_info.yaml
============================================================
Module bcbio raised an exception: Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/bin/multiqc", line 427, in multiqc
    output = mod()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/multiqc_bcbio/bcbio.py", line 111, in __init__
    if "coverage_avg_chart" in coverage_avg_plot:
TypeError: argument of type 'NoneType' is not iterable
============================================================
[INFO   ]        samtools : Found 1 stats reports
[INFO   ]        samtools : Found 1 idxstats reports
[INFO   ]        bcftools : Found 1 stats reports
[INFO   ]          snpeff : Found 1 reports
[INFO   ]          fastqc : Found 1 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : ../../bcbiotx/tmpu8rvWt/multiqc_report.html
[INFO   ]         multiqc : Data        : ../../bcbiotx/tmpu8rvWt/multiqc_data
[INFO   ]         multiqc : MultiQC complete
' returned non-zero exit status 1
' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Simone;
Apologies about the issue. The latest bcbio/bcbio Docker container was a little of date and didn't have the fix for this problem. I've pushed a fix to docker hub so if you get the latest container with `docker pull bcbio/bcbio` and re-run it should hopefully avoid the issue. Sorry about the out of date container and please feel free to reopen if you run into any other issues.

**Comment by coughls** [comment]
Thanks very much for the fast response Brad. Will give this a whirl.
